- name: git clone bin repository
  sudo: no
  git:
    repo=https://github.com/hdknr/bin.git
    dest=/home/{{ user }}/bin
    version=centos
    accept_hostkey=yes
- name: setup bin
  sudo: no
  shell: >
    {{ item }}
    chdir="/home/{{ user }}"
  with_items:
    - bin/setup/setup.bash
  ignore_errors: True  
