---
- name: download libevent source
  sudo: true
  get_url:
    url=http://downloads.sourceforge.net/project/levent/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz
    dest="{{ src_dir }}/libevent-2.0.22-stable.tar.gz"

- name: extract libevent source
  sudo: true
  unarchive:
    src="{{ src_dir }}/libevent-2.0.22-stable.tar.gz"
    dest="{{ src_dir }}"
    copy=no

- name: install libevent
  sudo: true
  shell: >
    {{ item }}
    chdir="{{ src_dir }}/libevent-2.0.22-stable"
    creates=/usr/lib64/libevent-2.0.so.5
  with_items:
    - ./configure
    - make
    - sudo make install
    - sudo ln -s /usr/local/lib/libevent-2.0.so.5 /usr/lib64/libevent-2.0.so.5
  notify: add path to shared libraries
